export default TIER = {
  CHALLENGER: 'CHALLENGER',
  GRANDMASTER: 'GRANDMASTER',
  MASTER: 'MASTER',
  DIAMOND: 'DIAMOND',
  PLATINUM: 'PLATINUM',
  GOLD: 'GOLD',
  SILVER: 'SILVER',
  BRONZE: 'BRONZE',
  IRON: 'IRON'
}
